#ifndef PROCESSOUTPUTTHREAD_HPP_WJRE9WEJR9IJWEROGIJOWERG
#define PROCESSOUTPUTTHREAD_HPP_WJRE9WEJR9IJWEROGIJOWERG


class ProcessOutputThread
{
    public:
};

#endif // PROCESSOUTPUTTHREAD_HPP_WJRE9WEJR9IJWEROGIJOWERG
